---
title: "Homework 6"
author: "Thiago de Araujo - UNI tbd2117"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

### Problem 1

Loading homicide data, creating `city_state` variable, binary `homicide_solve`, omiting specific cities, limiting analysis for whom `victim_race` is `white` or `black`, and `victim_age` numeric.

```{r, message = FALSE, warning = FALSE}
homicide = 
  read_csv("./data/homicide-data.csv") %>% 
  mutate(city_state = str_c(city, ", ", state)) %>% 
  filter(
    !city_state == c("Tulsa, AL", "Dallas, TX", "Phoenix, AZ", "Kansas City, MO"),
    victim_race == c("White", "Black")
  ) %>% 
  mutate(
    victim_age = as.numeric(victim_age),
    homicide_solved = case_when(
                        disposition %in% c("Open/No arrest", "Closed without arrest") ~ 0,
                        disposition == "Closed by arrest" ~ 1
                      )
  )
```

Estimated adjusted **odds ratio** for solving homicides comparing non-white victims to white victims keeping all other variables fixed.

```{r}
homicide %>% 
  filter(city_state == "Baltimore, MD") %>%
  mutate(
    victim_race = fct_relevel(victim_race, "White")
  ) %>% 
  glm(
    homicide_solved ~ victim_age + victim_sex + victim_race, 
    family = binomial(link = "logit"),
    data = .) %>% 
  broom::tidy() %>%
  filter(term == "victim_raceBlack") %>% 
  mutate(
    OR = exp(estimate),
    UCL = exp(estimate + (1.96*std.error)),
    LCL = exp(estimate - (1.96*std.error)),
    OR = round(OR, 2),
    UCL = round(UCL, 2),
    LCL = round(LCL, 2),
    "OR (95%CI)" = paste(OR, " (", LCL,"-",UCL,")", sep = ""),
    term = str_replace(term, "victim_raceBlack", "Non-white vs. white victims ")
  ) %>% 
  select(term, "OR (95%CI)") %>% 
  knitr::kable()
```

